urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^accounts/', include('registration.urls')),
    (r'^games/', include('games.urls')),
    (r'^vote', include('vote.urls')),
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', direct_to_template, {'template': 'static/home.html'}, name='home'),
    url(r'^how$', direct_to_template, {'template': 'static/how.html'}, name='how'),
    url(r'^rules$', direct_to_template, {'template': 'static/rules.html'}, name='rules'),
    url(r'^fineprint$', direct_to_template, {'template': 'static/fineprint.html'}, name='fineprint'),
    url(r'^prizes$', direct_to_template, {'template': 'static/prizes.html'}, name='prizes'),
    url(r'^judges$', direct_to_template, {'template': 'static/judges.html'}, name='judges'),
    url(r'^judging$', direct_to_template, {'template': 'static/judging.html'}, name='judging'),
    url(r'^resources$', direct_to_template, {'template': 'static/resources.html'}, name='resources'),
)

if settings.DEBUG:
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
          {'document_root': settings.MEDIA_ROOT}),
    )

apps/games/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from core.models import ModelBase, TimestampMixin


class Game(ModelBase, TimestampMixin):
    """The game model."""
    creator = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    url = models.URLField()
    source = models.URLField(blank=True)
    resources = models.TextField(blank=True)
    is_approved = models.NullBooleanField(default=None, blank=True,
                                          db_index=True)
    reviewed_by = models.ForeignKey(User, related_name='reviewed',
                                    null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Game, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('games.view', args=[self.id, self.slug])


class Screenshot(ModelBase, TimestampMixin):
    """A game screenshot."""
    game = models.ForeignKey(Game)
    file = models.ImageField(upload_to=settings.IMAGE_UPLOAD_PATH)

    def __unicode__(self):
        name = self.file.url.split('/')[-1]
        return u'%s: %s' % (self.game, name)

    def get_absolute_url(self):
        return self.file.url

templates/base.html
{% load tags %}
{% load bundler_tags %}
{% load waffle_tags %}
<!-- You are in a twisting series of little tubes, all alike. -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Mozilla Labs - Game On 2010</title>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% load_bundle "styles-min" %}
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/media/css/ie.css"/>
    <![endif]-->
  </head>
  <body class="{% block class %}{% endblock %}">
    <div id="page">
      <header class="menu">
          <a class="toplogo" href="http://www.mozillalabs.com/gaming/" target="_blank">
            <img src="{{ MEDIA_URL }}img/logo.png" border="0">
          </a>
          {% navigation %}
          <section id="auth">
            {% if user.is_authenticated %}
              signed in as {{ user.username }} |
              {% waffle allow_submissions %}
                <a href="{% url games.mine %}">your games</a>|
              {% else %}
                {% if user.game_set.exists %}
                  <a href="{% url games.mine %}">your games</a>|
                {% endif %}
              {% endwaffle %}
              {% waffle allow_voting %}
                <a href="{% url vote.ballot %}">your votes</a>|
              {% endwaffle %}
              <a href="{% url auth_logout %}?next=/">logout</a>
            {% else %}
              <a class="login" href="{% url auth_login %}">login</a>
              or
              <a class="join" href="{% url registration_register %}">sign up</a>
            {% endif %}
          </section>
      </header>

      {% if messages %}
        <ul id="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      <div id="content">
        {% block content %}

        {% endblock %}
      </div>

      <footer>
        <a href="http://www.mozillalabs.com"><img class="logo" src="{{ MEDIA_URL }}img//labs-logo.png" border="0"></a>
        Copyright &copy; 2005-2010 Mozilla. All rights reserved.
        <a href="http://www.mozilla.com/en-US/privacy-policy.html">Privacy Policy</a>
        <a href="http://www.mozilla.com/en-US/about/legal.html">Legal Notices</a>
      </footer>
    </div>
    {% load_bundle "scripts-min" %}
    {% deferred_content %}
  </body>
</html>

templates/navigation.html
<nav>
{% for name, path in menu %}
{% if location == path %}
  <span class="selected">{{ name }}</span>
{% else %}
  <a href="{{ path }}">{{ name }}</a>
{% endif %}
{% endfor %}
<a href="http://mozillalabs.com/gaming/">Blog</a>
</nav>