apps/games/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('games.views',
    url(r'^$', 'view_list', name='games.view_list'),
    url(r'^(?P<game_id>\d+)/(?P<slug>[\w-]+)?', 'view', name='games.view'),
    url(r'^finalists$', 'finalists', name='games.finalists'),
    url(r'^winners$', 'winners', name='games.winners'),
    url(r'^mine$', 'mine', name='games.mine'),
    url(r'^create', 'create', name='games.create'),
    url(r'^edit/(?P<game_id>\d+)$', 'edit', name='games.edit'),
    url(r'^delete/(?P<game_id>\d+)$', 'delete', name='games.delete'),
    url(r'^screenshots/(?P<game_id>\d+)$', 'screenshots',
        name='games.screenshots'),
    url(r'^screenshots/(?P<game_id>\d+)/delete/(?P<screenshot_id>\d+)$',
        'screenshot_delete', name='games.screenshot_delete')
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^accounts/', include('registration.urls')),
    (r'^games/', include('games.urls')),
    (r'^vote', include('vote.urls')),
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', direct_to_template, {'template': 'static/home.html'}, name='home'),
    url(r'^how$', direct_to_template, {'template': 'static/how.html'}, name='how'),
    url(r'^rules$', direct_to_template, {'template': 'static/rules.html'}, name='rules'),
    url(r'^fineprint$', direct_to_template, {'template': 'static/fineprint.html'}, name='fineprint'),
    url(r'^prizes$', direct_to_template, {'template': 'static/prizes.html'}, name='prizes'),
    url(r'^judges$', direct_to_template, {'template': 'static/judges.html'}, name='judges'),
    url(r'^judging$', direct_to_template, {'template': 'static/judging.html'}, name='judging'),
    url(r'^resources$', direct_to_template, {'template': 'static/resources.html'}, name='resources'),
)

if settings.DEBUG:
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
          {'document_root': settings.MEDIA_ROOT}),
    )

apps/games/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from core.models import ModelBase, TimestampMixin


class Game(ModelBase, TimestampMixin):
    """The game model."""
    creator = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    url = models.URLField()
    source = models.URLField(blank=True)
    resources = models.TextField(blank=True)
    is_approved = models.NullBooleanField(default=None, blank=True,
                                          db_index=True)
    reviewed_by = models.ForeignKey(User, related_name='reviewed',
                                    null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Game, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('games.view', args=[self.id, self.slug])


class Screenshot(ModelBase, TimestampMixin):
    """A game screenshot."""
    game = models.ForeignKey(Game)
    file = models.ImageField(upload_to=settings.IMAGE_UPLOAD_PATH)

    def __unicode__(self):
        name = self.file.url.split('/')[-1]
        return u'%s: %s' % (self.game, name)

    def get_absolute_url(self):
        return self.file.url

apps/games/forms.py
from django import forms
from django.conf import settings
from django.core.files.images import get_image_dimensions

from games.models import Game, Screenshot


MAX_WIDTH, MAX_HEIGHT = map(int,
                            settings.SCREENSHOTS_MAX_DIMENSIONS.split('x'))


class GameForm(forms.ModelForm):
    accept = forms.BooleanField(required=True);
    class Meta(object):
        model = Game
        fields = ('name', 'description', 'url', 'source', 'resources')


class ScreenshotForm(forms.ModelForm):
    class Meta(object):
        model = Screenshot
        fields = ('file',)

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if not file:
            raise forms.ValidationError('You must upload an image!')

        _, _, ext = file.name.rpartition('.')
        if not ext.lower() in ('png', 'gif', 'jpg', 'jpeg'):
            raise forms.ValidationError('Invalid file type!')

        if file.size >> 10 > settings.SCREENSHOTS_MAX_SIZE:
            msg = 'The image was too big (%i KB)! The limit is %i KB.'
            raise forms.ValidationError(msg % (file.size >> 10,
                                               settings.SCREENSHOTS_MAX_SIZE))

        width, height = get_image_dimensions(file)
        if width > MAX_WIDTH:
            msg = 'The image was too wide (%ipx)! The limit is %ipx.'
            raise forms.ValidationError(msg % (width, MAX_WIDTH))
        if height > MAX_HEIGHT:
            msg = 'The image was too tall (%ipx)! The limit is %ipx.'
            raise forms.ValidationError(msg % (height, MAX_HEIGHT))
        return file

apps/games/views.py
from operator import or_

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from waffle.decorators import waffle

from core.template import render
from games.forms import GameForm, ScreenshotForm
from games.models import Game, Screenshot


@waffle('allow_submissions')
@login_required
def create(request):
    """Create a new game."""
    form = GameForm()

    if request.POST:
        form = GameForm(request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.creator = request.user
            new_game.save()

            messages.success(request, "Your game was successfully saved!")
            return HttpResponseRedirect(new_game.get_absolute_url())

    return render(request, 'games/create.html', {'form': form})


@waffle('allow_editing')
@login_required
def edit(request, game_id):
    """Edit an existing game."""
    game = get_object_or_404(Game, creator=request.user, pk=game_id)
    form = GameForm(instance=game)
    room_for_more = game.screenshot_set.count() < settings.SCREENSHOTS_MAX
    screenshot_form = ScreenshotForm()

    c = {'game': game,
         'form': form,
         'room_for_more': room_for_more,
         'screenshot_form': screenshot_form,
        }

    if request.POST:
        form = GameForm(request.POST, instance=game)
        c.update({'form': form})
        if form.is_valid():
            form.save()

            messages.success(request, "Your changes were saved!")
            return HttpResponseRedirect(game.get_absolute_url())

    return render(request, 'games/edit.html', c)


@waffle('allow_deleting')
@login_required
def delete(request, game_id):
    """Delete an existing game."""

    game = get_object_or_404(Game, id=game_id, creator=request.user)

    if request.POST:
        msg = 'You have deleted the game "%s".' % game.name
        game.delete()

        messages.success(request, msg)
        return HttpResponseRedirect(reverse('games.view_list'))

    return render(request, 'games/delete.html', {'game': game})


def view(request, game_id, slug=None):
    """View one game. It must be approved or yours."""
    filters = []
    user = request.user if request.user.is_authenticated() else None
    if user and not user.is_superuser:
        filters.append(Q(creator=user))
    if not user or not user.is_superuser:
        filters.append(Q(is_approved=True))

    game = get_object_or_404(Game,
        reduce(or_, filters, Q()),
        id=game_id)
    return render(request, 'games/view.html', {'game': game})


@waffle('allow_gallery')
def view_list(request):
    """View a list of games."""
    # TODO: Paginate.
    filters = []
    user = request.user if request.user.is_authenticated() else None
    if user and not user.is_superuser:
        filters.append(Q(creator=user))
    if not user or not user.is_superuser:
        filters.append(Q(is_approved=True))

    games = Game.objects.filter(reduce(or_, filters, Q())).order_by('name')
    return render(request, 'games/list.html', {'games': games})


@waffle('allow_gallery')
def finalists(request):
    """View the list of finalists."""
    games = (Game.objects.filter(id__in=settings.FINALIST_LIST)
             .order_by('name'))
    return render(request, 'games/finalists.html', {'games': games})


@waffle('allow_gallery')
def winners(request):
    """View the list of winners."""
    return render(request, 'games/winners.html')


@login_required
def mine(request):
    """View your own games."""
    games = request.user.game_set.all()
    return render(request, 'games/mine.html', {'games': games})


@login_required
def screenshots(request, game_id):
    """View/edit screenshots for a game."""
    game = get_object_or_404(Game, id=game_id, creator=request.user)
    room_for_more = game.screenshot_set.count() < settings.SCREENSHOTS_MAX
    form = ScreenshotForm()

    game = get_object_or_404(Game, creator=request.user, pk=game_id)
    form = GameForm(instance=game)
    room_for_more = game.screenshot_set.count() < settings.SCREENSHOTS_MAX
    screenshot_form = ScreenshotForm()


    if request.POST and room_for_more:
        screenshot_form = ScreenshotForm(request.POST, request.FILES)
        if screenshot_form.is_valid():
            new_screenshot = screenshot_form.save(commit=False)
            new_screenshot.game = game
            new_screenshot.save()

            messages.success(request, "Your screenshot has been uploaded!")
            return HttpResponseRedirect(reverse('games.edit',
                                                args=[game.id]))
    c = {'game': game,
         'form': form,
         'room_for_more': room_for_more,
         'screenshot_form': screenshot_form,
    }
    return render(request, 'games/edit.html', c)


@login_required
def screenshot_delete(request, game_id, screenshot_id):
    """Delete a screenshot."""
    game = get_object_or_404(Game, id=game_id, creator=request.user)
    screenshot = get_object_or_404(Screenshot, id=screenshot_id, game=game)

    if request.POST:
        msg = 'You have deleted the screenshot %s!' % screenshot
        screenshot.delete()

        messages.success(request, msg)
        return HttpResponseRedirect(reverse('games.screenshots',
                                            args=[game.id]))

    c = {'game': game, 'screenshot': screenshot}
    return render(request, 'games/screenshot_delete.html', c)

apps/games/templates/games/base.html
{% extends "base.html" %}

{% block class %}games{% endblock %}

apps/games/templates/games/create.html
{% extends "games/base.html" %}

{% block class %}form{% endblock %}

{% block content %}
  <h1>Submit a Game</h1>
  {% if form.errors %}
    <ul class="errorlist">
      <li>Please fix the errors and submit again.</li>
    </ul>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <ul>
      <!-- {{ form.as_ul }} -->
      <li>{{ form.name.errors }}{{ form.name.label_tag }}{{ form.name }}</li>
      <li>{{ form.description.errors }}{{ form.description.label_tag }}{{ form.description }}</li>
      <li>{{ form.url.errors }}<label for="id_url">URL of the game:</label>{{ form.url }}</li>
      <li>
        {{ form.source.errors }}
        <label for="id_source" class="optional">
          URL of the source code:
        </label>{{ form.source }}
      </li>
      <li>
        <label for="id_resources" class="optional">
          Describe the tools, libraries and other resources you used in the
          making of this game:
        </label>{{ form.resources }}
      </li>
      {{ form.accept.errors }}
      {{ form.accept }}<label>I accept the <a target="_blank" href="/fineprint">Game On! 2010 Terms and Conditions</a></label>
    </ul>
    <input type="submit" value="Submit your game" />
  </form>
{% endblock %}

apps/games/templates/games/delete.html
{% extends "games/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <h1>Delete game?</h1>
    <p>You are about to delete the game <em>{{ game.name }}</em>.
      <strong>This cannot be undone!</strong> Are you sure?</p>

    <input type="submit" name="delete" value="Yes, delete it!"/>
    <a href="{{ game.get_absolute_url }}">Cancel</a>
  </form>
{% endblock%}

apps/games/templates/games/edit.html
{% extends "games/base.html" %}

{% block content %}
  <h1>Details</h1>
  <section class="screenshots">
    <h2>Screenshots</h2>
    <ul class="screenshots">
    {% for screenshot in game.screenshot_set.all %}
      <li>
        <img src="{{ screenshot.get_absolute_url }}"/>
        <a href="{% url games.screenshot_delete game.id,screenshot.id %}"
          class="screenshot-delete">Delete</a>
      </li>
    {% empty %}
      <li>No Screenshots Available</li>
    {% endfor %}
    </ul>

    {% if room_for_more %}
      <form method="post" action="{% url games.screenshots game.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Upload a new screenshot</h3>
        <ul class="screenshot-form">
          {{ screenshot_form.as_ul }}
        </ul>
        <input type="submit" value="Upload">
      </form>
    {% endif %}
  </section>

  {% if form.errors %}
    <ul class="errorlist">
      <li>Please fix the errors and submit again.</li>
    </ul>
  {% endif %}
  <form method="post" action="{% url games.edit game.id %}">
    {% csrf_token %}
    <ul>
      <!-- {{ form.as_ul }} -->
      <li>{{ form.name.errors }}{{ form.name.label_tag }}{{ form.name }}</li>
      <li>{{ form.description.errors }}{{ form.description.label_tag }}{{ form.description }}</li>
      <li>{{ form.url.errors }}<label for="id_url">URL of the game:</label>{{ form.url }}</li>
      <li>
        {{ form.source.errors }}
        <label for="id_source" class="optional">
          URL of the source code:
        </label>{{ form.source }}
      </li>
      <li>
        <label for="id_resources" class="optional">
          Describe the tools, libraries and other resources you used in the
          making of this game:
        </label>{{ form.resources }}
      </li>
      <input name="{{ form.accept.html_name }}" type="hidden" value="true">
    </ul>
    <input type="submit" value="Save your changes" />
  </form>
{% endblock %}

apps/games/templates/games/finalists.html
{% load waffle_tags %}
{% extends "games/base.html" %}
{% load waffle_tags %}

{% block content %}
<h3>
  {% if settings.FINALIST_LIST %}
    <a href="{% url games.view_list %}">See all the entries &raquo;</a><br/>
  {% endif %}
  {% waffle allow_voting %}
    <a href="{% url vote.ballot %}">Vote on the Community Prize &raquo;</a>
  {% endwaffle %}
</h3>
  <h1>Finalists</h1>
  <article class="tile-list">
  {% for game in games %}
    {% include "games/game_listing.html" %}
  {% endfor %}
  </article>
{% endblock %}

apps/games/templates/games/game_listing.html
{% load waffle_tags %}

<section class="game" id="game-{{ game.id }}">
  <div class="thumb">
    {% if game.screenshot_set.all %}
      <div style="background-image: url({{ game.screenshot_set.all.0.get_absolute_url }});">
    {% else %}
      <div>
    {% endif %}
    </div>
  </div>
  <h2><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></h2>
  <p>{{ game.description }}</p>
  <nav>
    <a class="action" target="_blank" href="{{ game.url }}">Play</a>
    {% if game.source %}
      <a class="action" href="{{ game.source }}">See the source</a>
    {% endif %}
    {% waffle allow_editing %}
      {% if game.creator == request.user %}
        <a class="action" href="{% url games.edit game.id %}">Edit</a>
      {% endif %}
    {% endwaffle %}
  </nav>
</section>

apps/games/templates/games/list.html
{% extends "games/base.html" %}

{% block content %}
<h3>
  <a href="{% url games.winners %}">See the winners! &raquo;</a><br/>
</h3>
  <h1>Game Gallery</h1>
  <article class="tile-list">
  {% for game in games %}
    {% include "games/game_listing.html" %}
  {% endfor %}
  </article>
{% endblock %}

apps/games/templates/games/mine.html
{% load waffle_tags %}
{% extends "games/base.html" %}
{% load waffle_tags %}

{% block content %}
  <h1>My Games</h1>
  <article class="tile-list">
  {% for game in games %}
    {% include "games/game_listing.html" %}
  {% empty %}
    <h2>You haven't submitted any games yet.</h2>
  {% endfor %}
  </article>
  {% waffle allow_submissions %}
  <h3><a href='{% url games.create %}'>Submit a new game</a></h3>
  {% endwaffle %}
{% endblock %}

apps/games/templates/games/screenshot_delete.html
{% extends "games/base.html" %}

{% block class %}screenshots{% endblock %}

{% block content %}
  <h1>Delete screenshot</h1>
  <p><b>Are you sure you want to delete the screenshot? This cannot be undone!</b></p>
  <img src="{{ screenshot.get_absolute_url }}"/>
  <form method="post">
    {% csrf_token %}
    <p>
      <input type="submit" value="Delete it!"/> or <b><a href="{% url games.edit game.id %}">Cancel</a></b>
    </p>
  </form>

{% endblock %}

apps/games/templates/games/view.html
{% extends "games/base.html" %}
{% load waffle_tags %}

{% block content %}
  <h1>{{ game.name }}</h1>
  <article class="game single">
    <section class="screenshots">
      <h2>Screenshots</h2>
      <ul class="screenshots">
      {% for screenshot in game.screenshot_set.all %}
        <li id="screenshot-{{ screenshot.id }}">
          <img src="{{ screenshot.get_absolute_url }}">
        </li>
      {% empty %}
        <li>No Screenshots Available</li>
        {% waffle allow_editing %}
          {% if game.creator == request.user %}
            <h3><a href="{% url games.edit game.id %}">Add Screenshots</a></h3>
          {% endif %}
        {% endwaffle %}
      {% endfor %}
      </ul>
    </section>

    <section class="description">
      <ul class="links">
        <li><a class="action" href="{{ game.url }}">Play the game</a></li>
        {% if game.source %}
          <li><a class="action" href="{{ game.source }}">See the source</a></li>
        {% endif %}
        {% waffle allow_editing %}
          {% if game.creator == request.user %}
            <li><a class="action" href="{% url games.edit game.id %}">Edit</a></li>
          {% endif %}
        {% endwaffle %}
      </ul>

      <h2>Description</h2>
      {{ game.description|linebreaks }}

      {% if game.resources %}
        <h2>Resources Used</h2>
        {{ game.resources|linebreaks }}
      {% endif %}
    </section>

    {% if not game.screenshot_set.all %}
    {% endif %}

  </article>
{% endblock %}

apps/games/templates/games/winners.html
{% extends "base.html" %}

{% load flatblock_tags %}

{% block class %}prizes winners copy{% endblock %}

{% block content %}
  <h1>High Scores</h1>
  <h2>Congratulations to the bit-slingers, pixel-wranglers, and JavaScript junkies listed
      here for showing the world what the Web can do!</h2>
  <section class="grandprize">
    <h2>BEST OVERALL</h2>
    <section class="game">
      <h2><a href="/games/130/marble-run">MARBLE RUN</a></h2>
      <h4>by <span>stravid</span></h4>
      <div class="thumb">
        <img src="/media/uploads/marblerun.png">
      </div>
      <div class="button">
        <a target="_blank" href="http://marblerun.at/"><br/>Play Now!</a>
      </div>
    </section>
  </section>
  <section class="categoryprizes">
    <h2>CATEGORY PRIZES</h2>
    <ul class="categories">
      <li>
        <hgroup>
          <h2><a href="/games/133/far-7">FAR 7</a></h2>
          <h3>Best Technology</h3>
          <h4>by <span>Sontan</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://far7.by/">Play Now!</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2><a href="/games/130/marble-run">MARBLE RUN</a></h2>
          <h3>Best Web-iness</h3>
          <h4>by <span>stravid</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://marblerun.at/">Play Now!</a>
            <a class="action" href="https://github.com/MathiasPaumgarten/marblerun">See the source</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2><a href="/games/169/sketchout">Sketchout</a></h2>
          <h3>Best Aesthetics</h3>
          <h4>by <span>Fi</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://sketch-out.appspot.com/">Play Now!</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2><a href="/games/72/favimon">Favimon</a></h2>
          <h3>Most Original</h3>
          <h4>by <span>oulipian</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://www.favimon.com/">Play Now!</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2><a href="/games/148/websnooker">Websnooker</a></h2>
          <h3>Most Polished</h3>
          <h4>by <span>leek</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://beta.websnooker.com/">Play Now!</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2 class="tiny"><a href="/games/149/robots-are-people-too">Robots Are People Too</a></h2>
          <h3>Most Fun</h3>
          <h4>by <span>rapt</span></h4>
          <nav>
            <a class="action" target="_blank" href="http://raptjs.heroku.com/">Play Now!</a>
            <a class="action" href="https://github.com/evanw/rapt">See the source</a>
          </nav>
        </hgroup>
      </li>
      <li>
        <hgroup>
          <h2><a href="/games/126/z-type">Z-Type</a></h2>
          <h3>Community Choice</h3>
          <h4>by <span>phoboslab</span></h4>
          <nav>
            <a href="http://www.phoboslab.org/ztype/" target="_blank" class="action">Play Now!</a>
          </nav>
        </hgroup>
      </li>
    </ul>
  </section>
{% endblock %}